---
kind: pipeline
name: default

platform:
  os: linux

steps:
- name: test
  image: python:3.7.3-alpine3.9
  commands:
  - pip install --no-cache-dir -r webapp/requirements.txt
  - pytest webapp/
...