---
kind: pipeline
name: default

platform:
  os: linux

steps:
- name: test
  image: python:3.7.3-alpine3.9
  commands:
  - apk add make
  - make install
  - make test

- name: build image
  image: plugins/docker
  settings:
    repo: amadil/test-webapp-gunicorn
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
...